return {
    -- 'jose-elias-alvarez/null-ls.nvim',
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "mason.nvim",
    -- },
    -- opts = function()
    --     local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
    --     local null_ls = require("null-ls")
    --
    --     return {
    --         sources = {
    --             -- null_ls.builtins.diagnostics.eslint,
    --             -- null_ls.builtins.formatting.prettier,
    --             null_ls.builtins.formatting.editorconfig_checker,
    --         },
    --
    --         on_attach = function(client, bufnr)
    --             if client.supports_method("textDocument/Formatting") then
    --                 vim.api.nvim_clear_autocmds({
    --                     group = augroup,
    --                     buffer = bufnr,
    --                 })
    --                 vim.api.nvim_create_autocmd("BufWritePre", {
    --                     group = augroup,
    --                     buffer = bufnr,
    --
    --                     callback = function()
    --                         vim.lsp.buf.format({ bufnr = bufnr })
    --                     end,
    --                 })
    --             end
    --         end
    --     }
    -- end,
}
