return {
    -- "nvim-tree/nvim-tree.lua",
    -- version = "*",
    -- lazy = false,
    -- dependencies = {
    --     "nvim-tree/nvim-web-devicons",
    -- },
    -- init = function()
    --     -- disable netrw at the very start of your init.lua
    --     vim.g.loaded_netrw = 1
    --     vim.g.loaded_netrwPlugin = 1
    --
    --     -- set termguicolors to enable highlight groups
    --     -- vim.opt.termguicolors = true
    --
    --     Map('n', '<C-n>', ':NvimTreeToggle<CR>')
    -- end,
    -- config = function()
    --     require("nvim-tree").setup({
    --         sort = {
    --             sorter = "case_sensitive",
    --         },
    --         view = {
    --             width = 40,
    --         },
    --         renderer = {
    --             group_empty = true,
    --         },
    --         filters = {
    --             dotfiles = true,
    --         },
    --     })
    -- end,
}
